# Generated by Django 5.2.8 on 2025-11-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_remove_curso_quantidade_horas_cursodisciplina_and_more'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='cursos',
            field=models.ManyToManyField(blank=True, to='curso.curso'),
        ),
    ]
