# Generated by Django 5.2.8 on 2025-11-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_cursos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='materia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
