# Generated by Django 5.2.6 on 2025-09-30 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Presencas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario_entrada', models.TimeField()),
                ('horario_saida', models.TimeField()),
                ('alunos', models.ManyToManyField(through='presenca.PresencaAluno', to='aluno.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='presencaaluno',
            name='presenca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presenca.presencas'),
        ),
    ]
