# Generated by Django 5.2.8 on 2025-11-26 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0002_aula'),
        ('presenca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presencaaluno',
            name='presenca',
        ),
        migrations.AddField(
            model_name='presencaaluno',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplina.aula'),
        ),
        migrations.AddField(
            model_name='presencaaluno',
            name='horario_entrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presencaaluno',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presencaaluno',
            name='presente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presencaaluno',
            name='tempo_total',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RegistroRFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=10)),
                ('presenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presenca.presencaaluno')),
            ],
        ),
        migrations.DeleteModel(
            name='Presencas',
        ),
    ]
