# Generated by Django 5.2.8 on 2025-11-27 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0002_remove_presencaaluno_presenca_presencaaluno_aula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrorfid',
            name='uid',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='registrorfid',
            name='presenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='presenca.presencaaluno'),
        ),
    ]
