# Generated by Django 5.2.8 on 2025-11-27 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_remove_curso_quantidade_horas_cursodisciplina_and_more'),
        ('disciplina', '0002_aula'),
        ('professor', '0002_professor_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.curso'),
        ),
        migrations.AddField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professor.professor'),
        ),
    ]
