# Generated by Django 5.2.8 on 2025-11-27 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_remove_curso_quantidade_horas_cursodisciplina_and_more'),
        ('disciplina', '0003_aula_curso_aula_professor'),
        ('horario', '0001_initial'),
        ('professor', '0003_alter_professor_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='horario_inicio',
        ),
        migrations.AddField(
            model_name='aula',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='horario.horarios'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='disciplina.disciplina'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas', to='professor.professor'),
        ),
    ]
