# Generated by Django 5.2.8 on 2025-11-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_uid'),
        ('curso', '0002_remove_curso_quantidade_horas_cursodisciplina_and_more'),
        ('disciplina', '0004_remove_aula_horario_fim_remove_aula_horario_inicio_and_more'),
        ('horario', '0001_initial'),
        ('professor', '0003_alter_professor_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(blank=True, to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='aula',
            name='horario_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aula',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aula',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.curso'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horario.horarios'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professor.professor'),
        ),
    ]
