# Generated by Django 5.2.8 on 2025-11-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_uid'),
        ('disciplina', '0005_aula_alunos_aula_horario_fim_aula_horario_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='carga_horaria',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='alunos',
            field=models.ManyToManyField(related_name='disciplinas_relacionadas', to='aluno.aluno'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
