# Generated by Django 5.2.8 on 2025-11-29 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0006_remove_disciplina_carga_horaria_disciplina_alunos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='alunos',
        ),
    ]
