# Generated by Django 5.2.8 on 2025-11-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0007_remove_aula_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='horario',
        ),
    ]
