# Generated by Django 5.2.8 on 2025-12-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0008_remove_aula_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='tempo_total',
            field=models.IntegerField(default=0),
        ),
    ]
