# Generated by Django 5.2.8 on 2025-12-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0009_aula_tempo_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='encerrada',
            field=models.BooleanField(default=False),
        ),
    ]
