# Generated by Django 4.2.26 on 2025-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0010_aula_encerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(default=60, help_text='Carga horária em horas'),
        ),
    ]
