# Generated by Django 4.2.26 on 2025-12-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0011_disciplina_carga_horaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(blank=True, help_text='Carga horária em horas', null=True),
        ),
    ]
