# Generated by Django 5.2.6 on 2025-09-30 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplinaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('disciplinas', models.ManyToManyField(through='horario.DisciplinaHorario', to='disciplina.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='disciplinahorario',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horario.horarios'),
        ),
    ]
