# Generated by Django 5.2.8 on 2025-11-27 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('disciplina', '0002_aula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='quantidade_horas',
        ),
        migrations.CreateModel(
            name='CursoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(through='curso.CursoDisciplina', to='disciplina.disciplina'),
        ),
    ]
