# Generated by Django 5.2.8 on 2025-11-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='uid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
